//! Maps and the interconnected world.
//!
//! Maps are plain data ([`MapData`]) loaded from `assets/maps/*.map.ron` by our
//! own RON reader (see [`crate::ron`]), so adding a level is just dropping a new
//! file. Each map is an ASCII grid plus a legend (solid / spike / rock / start
//! characters), a background colour, and the [`Door`]s off its four edges.
//!
//! Rooms connect Hollow-Knight style. Each edge carries a list of [`Door`]s: walk off
//! the edge and the door nearest the crossing swaps in its target room, dropping the
//! player at that door's recorded destination cell. (Teleporter pads, [`Teleport`], are
//! the other way across.) The camera is bounded to the current room
//! ([`crate::camera`]), so each room reads as its own space.

use std::collections::HashMap;

use bevy::asset::RenderAssetUsages;
use bevy::asset::io::Reader;
use bevy::asset::{AssetLoader, LoadContext};
use bevy::image::{CompressedImageFormats, ImageSampler, ImageType};
use bevy::prelude::*;

use crate::GameSet;
use crate::combat::{Bloodstain, ENEMY_HALF, ENEMY_KINDS, Enemy, LostEnergy};
use crate::hazards::{Hazard, RespawnPoint, RockSpawner, RockSprite, SPIKE_HALF};
use crate::health::{Health, Hurt};
use crate::input::PlayerIntent;
use crate::physics::{Solids, TILE};
use crate::player::{JumpState, PLAYER_HALF, Player, Velocity};
use crate::ron::{self, RonError};
use crate::state::GameState;
use crate::stats::{BenchAt, CharMenu, OverlayMode};

// `EMBEDDED_STORY_MAPS: &[(&str, &str)]` and `EMBEDDED_SPRITES: &[(&str, &[u8])]`,
// generated by `build.rs` — the shipped content baked into the binary.
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// A teleporter pad, stored as pure coordinates: stepping on the cell
/// `(origin_col, origin_row)` sends the player to room `to` at `(dest_col,
/// dest_row)`. All are grid cells (row 0 = top, as written in `tiles`). Because a
/// pad needs no grid glyph, it never competes with tile characters — a room may
/// hold many pads, and a pad may even target another cell in its own room.
#[derive(Clone)]
pub struct Teleport {
    pub origin_col: i32,
    pub origin_row: i32,
    pub to: String,
    pub dest_col: i32,
    pub dest_row: i32,
}

/// Types an enemy `E` glyph at cell `(col, row)` (grid coords, row 0 = top). The
/// `kind` indexes [`ENEMY_KINDS`](crate::combat::ENEMY_KINDS); an `E` with no
/// matching entry falls back to kind 0. One glyph, any number of types.
#[derive(Clone)]
pub struct EnemySpawn {
    pub kind: usize,
    pub col: i32,
    pub row: i32,
}

/// A one-way passage out of a room. Walking off the edge nearest `origin` loads room
/// `to` and drops the player at cell `dest`. An edge may carry several doors (e.g. a
/// top and a bottom doorway); the one used is whichever door's `origin` is nearest the
/// point where the player crossed. All cells are grid coords (row 0 = top). In RON a
/// door is the tuple `((origin_col, origin_row), "to", (dest_col, dest_row))`.
#[derive(Clone)]
pub struct Door {
    pub origin: (i32, i32),
    pub to: String,
    pub dest: (i32, i32),
}

/// Read a `(col, row)` cell tuple from a parsed value.
fn parse_cell(v: &ron::Value) -> Result<(i32, i32), RonError> {
    let c = v.as_list()?;
    if c.len() != 2 {
        return Err(RonError("a cell must be (col, row)".into()));
    }
    Ok((c[0].as_i32()?, c[1].as_i32()?))
}

/// Read one door tuple `((ocol, orow), "to", (dcol, drow))` from a parsed value.
fn parse_door(v: &ron::Value) -> Result<Door, RonError> {
    let items = v.as_list()?;
    if items.len() != 3 {
        return Err(RonError(
            "a door must be ((col, row), \"room\", (col, row))".into(),
        ));
    }
    Ok(Door {
        origin: parse_cell(&items[0])?,
        to: items[1].as_str()?.to_string(),
        dest: parse_cell(&items[2])?,
    })
}

/// How a [`Mover`] cycles its path once it reaches the last stop.
#[derive(Clone, Copy, PartialEq, Default)]
pub enum MoveMode {
    /// Travel to the last stop and halt there.
    Once,
    /// Cycle home → stops → home → … forever.
    #[default]
    Loop,
    /// Bounce back and forth along the path.
    PingPong,
}

/// A moving platform: a rigid group of `tiles` (cells, row 0 = top) whose anchor
/// (`tiles[0]`) travels through `path` carrying every tile by the same offset. It starts
/// at its `tiles` home, visits each `path` stop in order at `speed` px/s, pausing `rest`
/// ms at each, then continues per [`MoveMode`]. In RON:
/// `(tiles: [(c,r),…], path: [(c,r),…], mode: "loop", speed: 60, rest: 1000)`.
#[derive(Clone)]
pub struct Mover {
    pub tiles: Vec<(i32, i32)>,
    pub path: Vec<(i32, i32)>,
    pub mode: MoveMode,
    pub speed: f32,
    pub rest: f32,
}

/// Read one mover struct from a parsed value.
fn parse_mover(v: &ron::Value) -> Result<Mover, RonError> {
    let cells = |name: &str| -> Result<Vec<(i32, i32)>, RonError> {
        match v.try_field(name) {
            Some(list) => list.as_list()?.iter().map(parse_cell).collect(),
            None => Ok(Vec::new()),
        }
    };
    let tiles = cells("tiles")?;
    if tiles.is_empty() {
        return Err(RonError("a mover needs at least one tile".into()));
    }
    let mode = match v.try_field("mode").and_then(|m| m.as_str().ok()) {
        Some("once") => MoveMode::Once,
        Some("pingpong") => MoveMode::PingPong,
        _ => MoveMode::Loop,
    };
    Ok(Mover {
        tiles,
        path: cells("path")?,
        mode,
        speed: v
            .try_field("speed")
            .and_then(|s| s.as_f32().ok())
            .unwrap_or(60.0),
        rest: v
            .try_field("rest")
            .and_then(|s| s.as_f32().ok())
            .unwrap_or(0.0),
    })
}

/// Per-layer scenery selection: each parallax layer picks a **set** by name (empty =
/// that layer is absent), so a room can mix elements — e.g. a desert sky over forest
/// hills. The image for a layer is `"<set>/<layer>.png"`. See [`crate::scenery`].
#[derive(Clone, Default)]
pub struct Scenery {
    pub far: String,
    pub mid: String,
    pub near: String,
    pub fg: String,
}

/// Parse a `scenery` value: the per-layer struct `(far: "...", mid: ..., near: ..., fg:
/// ...)`, or a bare set name string (legacy) used for every layer.
fn parse_scenery(value: Option<&ron::Value>) -> Scenery {
    let Some(v) = value else {
        return Scenery::default();
    };
    if let Ok(set) = v.as_str() {
        let s = set.to_string();
        return Scenery {
            far: s.clone(),
            mid: s.clone(),
            near: s.clone(),
            fg: s,
        };
    }
    let layer = |name: &str| {
        v.try_field(name)
            .and_then(|x| x.as_str().ok())
            .unwrap_or("")
            .to_string()
    };
    Scenery {
        far: layer("far"),
        mid: layer("mid"),
        near: layer("near"),
        fg: layer("fg"),
    }
}

/// A combatant in a room's **arena** (its `fog_wall` list). These spawn only once the
/// player enters the room, and crossing the fog seals the exits until all are dead
/// (see [`crate::boss`]). `boss` picks a boss over a normal enemy of `kind`.
#[derive(Clone)]
pub struct ArenaSpawn {
    pub boss: bool,
    pub kind: usize,
    pub col: i32,
    pub row: i32,
}

/// One map's data, read from a `.map.ron` file by [`MapLoader`].
#[derive(Asset, TypePath, Clone)]
pub struct MapData {
    /// A human-friendly display name (empty → falls back to the file key).
    pub name: String,
    /// Characters treated as solid tiles (e.g. `"#"`).
    pub solid: String,
    /// Characters that are deadly ground spikes (e.g. `"^"`).
    pub spikes: String,
    /// Characters that spawn falling rocks (e.g. `"R"`).
    pub rocks: String,
    /// Doors off the top edge (empty = a solid / bottomless edge). See [`Door`].
    pub north: Vec<Door>,
    /// Doors off the bottom edge.
    pub south: Vec<Door>,
    /// Doors off the right edge.
    pub east: Vec<Door>,
    /// Doors off the left edge.
    pub west: Vec<Door>,
    /// Teleporter pads in this room (empty = none).
    pub teleports: Vec<Teleport>,
    /// Per-cell enemy types for `E` glyphs (cells without an entry use kind 0).
    pub enemies: Vec<EnemySpawn>,
    /// Arena combatants (empty = not an arena). Spawn on entry; crossing the room's
    /// fog (`F` glyphs) seals the exits until all of these are dead.
    pub fog_wall: Vec<ArenaSpawn>,
    /// If set, this arena **re-arms on a bench rest** (its foes respawn); otherwise it
    /// stays cleared permanently. Bosses persist regardless (their kill is saved).
    pub fog_respawn: bool,
    /// Moving platforms (empty = none). See [`Mover`].
    pub movers: Vec<Mover>,
    /// Per-layer parallax scenery for this room (mix-and-match; see [`Scenery`]).
    pub scenery: Scenery,
    /// Background (clear) colour as `[r, g, b]` in 0..1.
    pub bg: [f32; 3],
    /// The grid, one string per row (top to bottom).
    pub tiles: Vec<String>,
}

impl MapData {
    /// Build a map from RON text (see [`crate::ron`] for the supported subset).
    pub(crate) fn from_ron(text: &str) -> Result<Self, RonError> {
        let value = ron::from_str(text)?;

        let optional_str = |name: &str| -> Result<String, RonError> {
            match value.try_field(name) {
                Some(v) => Ok(v.as_str()?.to_string()),
                None => Ok(String::new()),
            }
        };

        let bg_list = value.field("bg")?.as_list()?;
        if bg_list.len() != 3 {
            return Err(RonError("bg must have 3 components".into()));
        }
        let bg = [
            bg_list[0].as_f32()?,
            bg_list[1].as_f32()?,
            bg_list[2].as_f32()?,
        ];

        let tiles = value
            .field("tiles")?
            .as_list()?
            .iter()
            .map(|v| Ok(v.as_str()?.to_string()))
            .collect::<Result<Vec<_>, RonError>>()?;

        let teleports = match value.try_field("teleports") {
            Some(list) => list
                .as_list()?
                .iter()
                .map(|t| {
                    Ok(Teleport {
                        origin_col: t.field("origin_col")?.as_i32()?,
                        origin_row: t.field("origin_row")?.as_i32()?,
                        to: t.field("to")?.as_str()?.to_string(),
                        dest_col: t.field("dest_col")?.as_i32()?,
                        dest_row: t.field("dest_row")?.as_i32()?,
                    })
                })
                .collect::<Result<Vec<_>, RonError>>()?,
            None => Vec::new(),
        };

        let enemies = match value.try_field("enemies") {
            Some(list) => list
                .as_list()?
                .iter()
                .map(|e| {
                    Ok(EnemySpawn {
                        kind: e.field("kind")?.as_i32()?.max(0) as usize,
                        col: e.field("col")?.as_i32()?,
                        row: e.field("row")?.as_i32()?,
                    })
                })
                .collect::<Result<Vec<_>, RonError>>()?,
            None => Vec::new(),
        };

        let fog_wall = match value.try_field("fog_wall") {
            Some(list) => list
                .as_list()?
                .iter()
                .map(|c| {
                    Ok(ArenaSpawn {
                        boss: c
                            .try_field("boss")
                            .and_then(|v| v.as_i32().ok())
                            .unwrap_or(0)
                            != 0,
                        kind: c.field("kind")?.as_i32()?.max(0) as usize,
                        col: c.field("col")?.as_i32()?,
                        row: c.field("row")?.as_i32()?,
                    })
                })
                .collect::<Result<Vec<_>, RonError>>()?,
            None => Vec::new(),
        };

        let fog_respawn = value
            .try_field("fog_respawn")
            .and_then(|v| v.as_i32().ok())
            .unwrap_or(0)
            != 0;

        let movers = match value.try_field("movers") {
            Some(list) => list
                .as_list()?
                .iter()
                .map(parse_mover)
                .collect::<Result<Vec<_>, RonError>>()?,
            None => Vec::new(),
        };

        // Each edge is a list of doors, `((ocol, orow), "to", (dcol, drow))`.
        let doors = |name: &str| -> Result<Vec<Door>, RonError> {
            match value.try_field(name) {
                Some(list) => list.as_list()?.iter().map(parse_door).collect(),
                None => Ok(Vec::new()),
            }
        };

        Ok(MapData {
            name: optional_str("name")?,
            solid: value.field("solid")?.as_str()?.to_string(),
            spikes: optional_str("spikes")?,
            rocks: optional_str("rocks")?,
            north: doors("north")?,
            south: doors("south")?,
            east: doors("east")?,
            west: doors("west")?,
            teleports,
            enemies,
            fog_wall,
            fog_respawn,
            movers,
            scenery: parse_scenery(value.try_field("scenery")),
            bg,
            tiles,
        })
    }

    fn bg_color(&self) -> Color {
        Color::srgb(self.bg[0], self.bg[1], self.bg[2])
    }

    /// The display name, or the file `key` when none has been set.
    pub(crate) fn display_name<'a>(&'a self, key: &'a str) -> &'a str {
        if self.name.is_empty() {
            key
        } else {
            &self.name
        }
    }

    /// Serialise back to the `.map.ron` text our reader accepts (for the editor).
    pub(crate) fn to_ron(&self) -> String {
        let rows: String = self
            .tiles
            .iter()
            .map(|row| format!("        \"{row}\",\n"))
            .collect();
        let teleports: String = self
            .teleports
            .iter()
            .map(|t| {
                format!(
                    "        (origin_col: {}, origin_row: {}, to: \"{}\", dest_col: {}, dest_row: {}),\n",
                    t.origin_col, t.origin_row, t.to, t.dest_col, t.dest_row
                )
            })
            .collect();
        let enemies: String = self
            .enemies
            .iter()
            .map(|e| {
                format!(
                    "        (kind: {}, col: {}, row: {}),\n",
                    e.kind, e.col, e.row
                )
            })
            .collect();
        let fog_wall: String = self
            .fog_wall
            .iter()
            .map(|c| {
                format!(
                    "        (boss: {}, kind: {}, col: {}, row: {}),\n",
                    i32::from(c.boss),
                    c.kind,
                    c.col,
                    c.row
                )
            })
            .collect();
        // Each edge renders as a list of door tuples, one per line.
        let door_list = |doors: &[Door]| -> String {
            doors
                .iter()
                .map(|d| {
                    format!(
                        "        (({}, {}), \"{}\", ({}, {})),\n",
                        d.origin.0, d.origin.1, d.to, d.dest.0, d.dest.1
                    )
                })
                .collect()
        };
        let north = door_list(&self.north);
        let south = door_list(&self.south);
        let east = door_list(&self.east);
        let west = door_list(&self.west);
        // Movers: a `(col, row)` cell list, then one struct per platform.
        let cell_list = |cells: &[(i32, i32)]| -> String {
            let inner: Vec<String> = cells.iter().map(|(c, r)| format!("({c}, {r})")).collect();
            format!("[{}]", inner.join(", "))
        };
        let movers: String = self
            .movers
            .iter()
            .map(|m| {
                let mode = match m.mode {
                    MoveMode::Once => "once",
                    MoveMode::PingPong => "pingpong",
                    MoveMode::Loop => "loop",
                };
                format!(
                    "        (tiles: {}, path: {}, mode: \"{}\", speed: {}, rest: {}),\n",
                    cell_list(&m.tiles),
                    cell_list(&m.path),
                    mode,
                    m.speed,
                    m.rest
                )
            })
            .collect();
        format!(
            "(\n    name: \"{}\",\n    solid: \"{}\",\n    spikes: \"{}\",\n    rocks: \"{}\",\n    \
             north: [\n{north}    ],\n    south: [\n{south}    ],\n    \
             east: [\n{east}    ],\n    west: [\n{west}    ],\n    \
             teleports: [\n{teleports}    ],\n    enemies: [\n{enemies}    ],\n    \
             fog_wall: [\n{fog_wall}    ],\n    fog_respawn: {},\n    \
             movers: [\n{movers}    ],\n    \
             scenery: (far: \"{}\", mid: \"{}\", near: \"{}\", fg: \"{}\"),\n    \
             bg: [{}, {}, {}],\n    tiles: [\n{rows}    ],\n)\n",
            self.name,
            self.solid,
            self.spikes,
            self.rocks,
            i32::from(self.fog_respawn),
            self.scenery.far,
            self.scenery.mid,
            self.scenery.near,
            self.scenery.fg,
            self.bg[0],
            self.bg[1],
            self.bg[2],
        )
    }

    /// Every room this map links out to (across all four edges).
    #[cfg(test)]
    fn linked_rooms(&self) -> impl Iterator<Item = &str> {
        [&self.north, &self.south, &self.east, &self.west]
            .into_iter()
            .flatten()
            .map(|d| d.to.as_str())
    }
}

/// Loads [`MapData`] from `assets/maps/*.map.ron` using our own RON reader, so the
/// game depends only on Bevy (no `serde`/`ron`/`bevy_common_assets`).
#[derive(Default, TypePath)]
struct MapLoader;

impl AssetLoader for MapLoader {
    type Asset = MapData;
    type Settings = ();
    type Error = RonError;

    async fn load(
        &self,
        reader: &mut dyn Reader,
        _settings: &(),
        _ctx: &mut LoadContext<'_>,
    ) -> Result<MapData, RonError> {
        let mut bytes = Vec::new();
        reader
            .read_to_end(&mut bytes)
            .await
            .map_err(|e| RonError(format!("read error: {e}")))?;
        let text = std::str::from_utf8(&bytes).map_err(|e| RonError(format!("not UTF-8: {e}")))?;
        MapData::from_ron(text)
    }

    fn extensions(&self) -> &[&str] {
        &["map.ron"]
    }
}

/// How the player should be placed when a room loads.
#[derive(Clone)]
pub(crate) enum Entry {
    /// The world's starting position (the `@` marker in the grid).
    Start,
    /// Arrived by walking through a [`Door`]; place the player at the door's
    /// destination cell `(col, row)` (grid coords, row 0 = top).
    Edge(i32, i32),
    /// Arrived through a teleporter; place the player at the destination cell
    /// `(col, row)` (grid coords, row 0 = top) recorded on the pad.
    Teleport(i32, i32),
    /// Respawned/loaded onto a bench at cell `(col, row)` (grid coords).
    Bench(i32, i32),
}

/// Tags every entity belonging to the current map (despawned on transition).
#[derive(Component)]
pub(crate) struct MapEntity;

/// A spawned teleporter pad: stepping onto it sends the player to room `to`, the
/// cell `dest` `(col, row)` in grid coords (row 0 = top).
#[derive(Component)]
pub(crate) struct Teleporter {
    to: String,
    dest: (i32, i32),
}

/// Whether teleporters are ready to fire. Disarmed on each teleport, on every room
/// load, and when the player respawns from damage (so respawning onto a pad can't
/// chain), and only re-armed once the player is [`TELEPORT_REARM`] from every pad.
#[derive(Resource)]
pub(crate) struct TeleportArmed(pub(crate) bool);

impl Default for TeleportArmed {
    fn default() -> Self {
        Self(true)
    }
}

/// Grid glyph marking a patrolling enemy spawn (its type comes from the room's
/// `enemies` array, by cell; cells without an entry use kind 0).
pub(crate) const ENEMY_GLYPH: char = 'E';
/// Grid glyph marking a bench: a checkpoint that saves the game, refills hearts,
/// resets enemies, and becomes the player's respawn point.
pub(crate) const BENCH_GLYPH: char = 'B';
/// Grid glyph for a **fog wall** cell: the mist marking an arena's threshold.
/// Entering a room whose `fog_wall` lists combatants seals the exits until they're all
/// dead (see [`crate::boss`]); the `F` cells just draw the mist.
pub(crate) const FOG_GLYPH: char = 'F';
/// Half-extents of a bench's "rest" trigger area.
const BENCH_HALF: Vec2 = Vec2::new(TILE * 0.5, TILE * 0.5);

/// A spawned bench, carrying its own grid cell so resting can record it as the
/// respawn point.
#[derive(Component)]
pub(crate) struct Bench {
    col: i32,
    row: i32,
}

/// The "press to rest" prompt shown above a bench the player is standing on.
#[derive(Component)]
struct BenchPrompt;

/// A menu-driven request for where to spawn when `Playing` next begins: the room,
/// and an optional bench cell (else the room's start marker). Consumed by
/// [`enter_playing`]; when unset, re-entering `Playing` (from the editor) just
/// reloads the current room.
#[derive(Resource, Default)]
pub(crate) struct PendingSpawn(pub(crate) Option<SpawnRequest>);

pub(crate) struct SpawnRequest {
    pub(crate) room: String,
    pub(crate) at_cell: Option<(i32, i32)>,
}
/// Half-extents of a teleporter's trigger area.
const TELEPORT_HALF: Vec2 = Vec2::new(TILE * 0.45, TILE * 0.5);
/// How far the player must move from a pad before it re-arms. Larger than the
/// trigger, so there's a dead zone (~1.5 tiles) between using a pad and it being
/// able to fire again — you must step clear before re-entering.
const TELEPORT_REARM: f32 = TILE * 1.5;

#[derive(Resource)]
pub(crate) struct GameAssets {
    pub(crate) maps: HashMap<String, Handle<MapData>>,
    /// Discovered room names, sorted (drives loading and the world map).
    pub(crate) room_names: Vec<String>,
    pub(crate) tile: Handle<Image>,
    pub(crate) player: Handle<Image>,
    pub(crate) spikes: Handle<Image>,
    pub(crate) portal: Handle<Image>,
    pub(crate) bench: Handle<Image>,
    /// One sprite sheet per [`ENEMY_KINDS`] entry (by index).
    pub(crate) enemy_sheets: Vec<Handle<Image>>,
    pub(crate) orb: Handle<Image>,
    pub(crate) slash: Handle<Image>,
    pub(crate) boss: Handle<Image>,
    /// Parallax scenery layers by file name (e.g. `"forest_meadow_far.png"`).
    pub(crate) scenery: HashMap<String, Handle<Image>>,
}

/// The room the player is currently in: its name, neighbours and pixel size.
#[derive(Resource, Default)]
pub(crate) struct CurrentRoom {
    pub(crate) name: String,
    north: Vec<Door>,
    south: Vec<Door>,
    east: Vec<Door>,
    west: Vec<Door>,
    size: Vec2,
}

/// The current room's pixel bounds, read by the camera to clamp itself. `snap`
/// asks the camera to jump (rather than glide) on the next frame after a load.
#[derive(Resource, Default)]
pub(crate) struct RoomView {
    pub size: Vec2,
    pub snap: bool,
}

/// Request to (re)load a map and place the player.
#[derive(Message, Clone)]
pub(crate) struct LoadMap {
    pub(crate) map: String,
    pub(crate) entry: Entry,
}

/// Brief window after a transition during which edges are ignored, so the player
/// doesn't immediately bounce back through the edge they just arrived at.
#[derive(Resource, Default)]
struct TransitionCooldown(f32);

/// The shipped campaign's level folder — used only by tests (the runtime reads the
/// embedded copy; see [`EMBEDDED_STORY_MAPS`]).
#[cfg(test)]
pub(crate) const SHIPPED_MAPS_DIR: &str = "assets/maps";
pub(crate) const START_MAP: &str = "r0_0";

/// Where the active save's rooms come from: the binary's embedded Story campaign, or
/// a Builder save's on-disk, editable copy.
#[derive(Resource, Default)]
pub(crate) enum LevelRoot {
    /// Read the shipped Story levels from [`EMBEDDED_STORY_MAPS`] (no `assets/` needed).
    #[default]
    Story,
    /// A Builder save's level directory (read from and written to on disk).
    Builder(String),
}

impl LevelRoot {
    /// The on-disk directory, if this is a Builder world (the editor writes here).
    pub(crate) fn dir(&self) -> Option<&str> {
        match self {
            LevelRoot::Story => None,
            LevelRoot::Builder(dir) => Some(dir),
        }
    }
}

/// A Builder slot's private level directory.
pub(crate) fn builder_maps_dir(slot: usize) -> String {
    format!("saves/builder{slot}/maps")
}

/// (Re)seed a Builder slot from the embedded Story levels and return its directory.
/// Wipes any previous contents so "New Game" over an old slot starts clean.
pub(crate) fn init_builder_world(slot: usize) -> String {
    let dir = builder_maps_dir(slot);
    let _ = std::fs::remove_dir_all(&dir);
    let _ = std::fs::create_dir_all(&dir);
    for (name, ron) in EMBEDDED_STORY_MAPS {
        let _ = std::fs::write(map_fs_path(&dir, name), ron);
    }
    dir
}

/// Filesystem path to a room's file under a Builder level directory.
pub(crate) fn map_fs_path(dir: &str, name: &str) -> String {
    format!("{dir}/{name}.map.ron")
}

/// Every `*.map.ron` in a Builder directory, sorted.
pub(crate) fn discover_rooms(dir: &str) -> Vec<String> {
    let mut names: Vec<String> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter_map(|entry| {
            entry
                .file_name()
                .to_str()
                .and_then(|n| n.strip_suffix(".map.ron"))
                .map(str::to_string)
        })
        .collect();
    names.sort();
    names
}
/// Grid character marking the player's start position in the starting room.
pub(crate) const START_MARKER: char = '@';
pub struct WorldPlugin;

impl Plugin for WorldPlugin {
    fn build(&self, app: &mut App) {
        app.init_asset::<MapData>()
            .register_asset_loader(MapLoader)
            .add_message::<LoadMap>()
            .init_resource::<Solids>()
            .init_resource::<TransitionCooldown>()
            .init_resource::<CurrentRoom>()
            .init_resource::<RoomView>()
            .init_resource::<TeleportArmed>()
            .init_resource::<PendingSpawn>()
            .init_resource::<LevelRoot>()
            .add_systems(Startup, load_assets)
            .add_systems(OnEnter(GameState::Loading), load_world)
            .add_systems(Update, wait_for_load.run_if(in_state(GameState::Loading)))
            .add_systems(
                OnEnter(GameState::Playing),
                (enter_playing, spawn_bench_prompt),
            )
            .add_systems(OnExit(GameState::Playing), despawn_bench_prompt)
            .add_systems(
                Update,
                (
                    handle_load_map,
                    tick_cooldown,
                    confine_to_arena.in_set(GameSet::Transitions),
                    detect_transitions.in_set(GameSet::Transitions),
                    detect_teleport.in_set(GameSet::Transitions),
                    bench_interact.in_set(GameSet::Transitions),
                )
                    .run_if(in_state(GameState::Playing)),
            );
    }
}

/// Decode PNG bytes into a live `Image` asset, keeping the game's crisp
/// nearest-neighbour sampling.
fn decode_png(images: &mut Assets<Image>, file: &str, bytes: &[u8]) -> Handle<Image> {
    let image = Image::from_buffer(
        bytes,
        ImageType::Extension("png"),
        CompressedImageFormats::NONE,
        true, // sRGB colour art
        ImageSampler::nearest(),
        RenderAssetUsages::RENDER_WORLD,
    )
    .unwrap_or_else(|e| panic!("decoding embedded PNG '{file}': {e:?}"));
    images.add(image)
}

/// Decode an embedded sprite by file name.
fn embedded_sprite(images: &mut Assets<Image>, file: &str) -> Handle<Image> {
    let bytes = EMBEDDED_SPRITES
        .iter()
        .find(|(name, _)| *name == file)
        .map(|(_, bytes)| *bytes)
        .unwrap_or_else(|| panic!("embedded sprite '{file}' not found"));
    decode_png(images, file, bytes)
}

fn load_assets(mut commands: Commands, mut images: ResMut<Assets<Image>>) {
    // Sprites are decoded from the embedded bytes; rooms come from the active save
    // (see `load_world`), so `maps`/`room_names` start empty here.
    commands.insert_resource(GameAssets {
        maps: HashMap::new(),
        room_names: Vec::new(),
        tile: embedded_sprite(&mut images, "tile.png"),
        player: embedded_sprite(&mut images, "player.png"),
        spikes: embedded_sprite(&mut images, "spikes.png"),
        portal: embedded_sprite(&mut images, "portal.png"),
        bench: embedded_sprite(&mut images, "bench.png"),
        enemy_sheets: ENEMY_KINDS
            .iter()
            .map(|k| embedded_sprite(&mut images, k.sheet))
            .collect(),
        orb: embedded_sprite(&mut images, "orb.png"),
        slash: embedded_sprite(&mut images, "slash.png"),
        boss: embedded_sprite(&mut images, "boss.png"),
        scenery: EMBEDDED_SCENERY
            .iter()
            .map(|(name, bytes)| (name.to_string(), decode_png(&mut images, name, bytes)))
            .collect(),
    });
    commands.insert_resource(RockSprite(embedded_sprite(&mut images, "rock.png")));
}

/// Load the active save's rooms into live `MapData` assets — the embedded Story
/// campaign, or a Builder save's on-disk copy. Runs on entering `Loading`, so it
/// always reflects the world the just-selected save points at.
fn load_world(
    level_root: Res<LevelRoot>,
    mut assets: ResMut<GameAssets>,
    mut maps: ResMut<Assets<MapData>>,
) {
    assets.maps.clear();
    assets.room_names.clear();

    let rooms: Vec<(String, MapData)> = match &*level_root {
        LevelRoot::Story => EMBEDDED_STORY_MAPS
            .iter()
            .filter_map(|(name, ron)| match MapData::from_ron(ron) {
                Ok(map) => Some((name.to_string(), map)),
                Err(e) => {
                    warn!("embedded room '{name}' failed to parse: {e}");
                    None
                }
            })
            .collect(),
        LevelRoot::Builder(dir) => discover_rooms(dir)
            .into_iter()
            .filter_map(|name| {
                let path = map_fs_path(dir, &name);
                match std::fs::read_to_string(&path).map(|t| MapData::from_ron(&t)) {
                    Ok(Ok(map)) => Some((name, map)),
                    _ => {
                        warn!("could not load room '{name}' from {path}");
                        None
                    }
                }
            })
            .collect(),
    };

    for (name, map) in rooms {
        let handle = maps.add(map);
        assets.maps.insert(name.clone(), handle);
        assets.room_names.push(name);
    }
    assets.room_names.sort();
}

fn wait_for_load(mut next: ResMut<NextState<GameState>>) {
    // Sprites are decoded up-front and rooms loaded in `load_world`, so there's
    // nothing async to wait on — head straight into play.
    next.set(GameState::Playing);
}

fn enter_playing(
    mut commands: Commands,
    assets: Res<GameAssets>,
    current: Res<CurrentRoom>,
    mut pending: ResMut<PendingSpawn>,
    mut health: ResMut<Health>,
    players: Query<(), With<Player>>,
    mut load: MessageWriter<LoadMap>,
) {
    // Spawn the player once; `handle_load_map` positions it for each room. (We
    // re-enter `Playing` after the level builder, so it may already exist.)
    if players.is_empty() {
        commands.spawn((
            Player,
            Velocity::default(),
            JumpState::default(),
            Sprite {
                image: assets.player.clone(),
                custom_size: Some(Vec2::new(24.0, 40.0)),
                ..default()
            },
            Transform::from_xyz(0.0, 0.0, 10.0),
        ));
    }

    // A menu-driven New Game / Load Game requests a room (and maybe a bench cell);
    // honour it and refill hearts. Otherwise we're returning from the editor — just
    // reload the current room, falling back to the start (the builder can move rooms).
    if let Some(req) = pending.0.take() {
        health.current = health.max;
        let entry = match req.at_cell {
            Some((col, row)) => Entry::Bench(col, row),
            None => Entry::Start,
        };
        let map = if assets.maps.contains_key(&req.room) {
            req.room
        } else {
            START_MAP.to_string()
        };
        load.write(LoadMap { map, entry });
        return;
    }

    let map = if assets.maps.contains_key(&current.name) {
        current.name.clone()
    } else if assets.maps.contains_key(START_MAP) {
        START_MAP.to_string()
    } else {
        assets.room_names.first().cloned().unwrap_or_default()
    };
    load.write(LoadMap {
        map,
        entry: Entry::Start,
    });
}

/// Where the player lands when a room loads, given how they entered it. Everything but
/// a fresh `Start` lands on a recorded destination cell (`cell`, already resolved to a
/// world centre and clamped in range): a door's `dest`, a teleporter pad, or a bench.
fn entry_position(entry: &Entry, start: Vec2, cell: Vec2) -> Vec2 {
    match entry {
        Entry::Start => start,
        Entry::Edge(..) | Entry::Teleport(..) | Entry::Bench(..) => cell,
    }
}

/// Spawn one enemy of `kind` at `pos` (the kind's sheet + tint; `anim` attaches the
/// atlas, `combat` drives the AI). Shared by the `E` glyph and arena combatants.
fn spawn_enemy(commands: &mut Commands, assets: &GameAssets, kind: usize, pos: Vec2) {
    let kind = kind.min(ENEMY_KINDS.len() - 1);
    commands.spawn((
        MapEntity,
        Enemy::new(kind),
        Hazard { half: ENEMY_HALF },
        Sprite {
            image: assets.enemy_sheets[kind].clone(),
            color: ENEMY_KINDS[kind].color,
            custom_size: Some(Vec2::splat(TILE)),
            ..default()
        },
        Transform::from_xyz(pos.x, pos.y, 2.0),
    ));
}

/// Spawn the entity for one grid glyph at `center`, returning `(entity, is_solid)` when
/// it's a standalone, **movable** cell (a solid, spike, bench, or rock spawner) so a
/// [`Mover`] can pick it up. Returns `None` for the start marker (which only sets
/// `start_pos`), enemies, fog, and empty cells — things a mover doesn't carry.
#[allow(clippy::too_many_arguments)] // distinct, glyph-specific spawn data
fn spawn_cell(
    commands: &mut Commands,
    assets: &GameAssets,
    map: &MapData,
    ch: char,
    col: i32,
    r: i32,
    center: Vec2,
    arena_armed: bool,
    start_pos: &mut Vec2,
) -> Option<(Entity, bool)> {
    if ch == START_MARKER {
        *start_pos = center;
        None
    } else if ch == ENEMY_GLYPH {
        // The type comes from the room's `enemies` array (by cell); an `E` with no entry
        // — or an out-of-range kind — uses the first type.
        let kind = map
            .enemies
            .iter()
            .find(|e| e.col == col && e.row == r)
            .map_or(0, |e| e.kind);
        spawn_enemy(commands, assets, kind, center);
        None
    } else if ch == BENCH_GLYPH {
        let e = commands
            .spawn((
                MapEntity,
                Bench { col, row: r },
                Sprite {
                    image: assets.bench.clone(),
                    custom_size: Some(Vec2::splat(TILE)),
                    ..default()
                },
                Transform::from_xyz(center.x, center.y, 1.0),
            ))
            .id();
        Some((e, false))
    } else if ch == FOG_GLYPH {
        // The mist is purely visual (you walk through it); the seal is the locked exits
        // below. Only show it while the arena is live.
        if arena_armed {
            crate::boss::spawn_fog_cell(commands, center);
        }
        None
    } else if map.solid.contains(ch) {
        let e = commands
            .spawn((
                MapEntity,
                Sprite {
                    image: assets.tile.clone(),
                    custom_size: Some(Vec2::splat(TILE)),
                    ..default()
                },
                Transform::from_xyz(center.x, center.y, 0.0),
            ))
            .id();
        Some((e, true))
    } else if map.spikes.contains(ch) {
        let e = commands
            .spawn((
                MapEntity,
                Hazard { half: SPIKE_HALF },
                Sprite {
                    image: assets.spikes.clone(),
                    custom_size: Some(Vec2::splat(TILE)),
                    ..default()
                },
                Transform::from_xyz(center.x, center.y, 1.0),
            ))
            .id();
        Some((e, false))
    } else if map.rocks.contains(ch) {
        // Stagger spawners so they don't all drop in sync.
        let mut timer = Timer::from_seconds(2.2, TimerMode::Repeating);
        timer.set_elapsed(std::time::Duration::from_secs_f32(
            (col as f32 * 0.41) % 2.2,
        ));
        let e = commands
            .spawn((
                MapEntity,
                RockSpawner { timer },
                Transform::from_xyz(center.x, center.y, 1.0),
            ))
            .id();
        Some((e, false))
    } else {
        None
    }
}

#[allow(clippy::too_many_arguments)] // a Bevy system; each param is a distinct query/resource
fn handle_load_map(
    mut commands: Commands,
    mut events: MessageReader<LoadMap>,
    map_assets: Res<Assets<MapData>>,
    assets: Res<GameAssets>,
    mut solids: ResMut<Solids>,
    mut cooldown: ResMut<TransitionCooldown>,
    mut current: ResMut<CurrentRoom>,
    mut room_view: ResMut<RoomView>,
    mut respawn: ResMut<RespawnPoint>,
    mut armed: ResMut<TeleportArmed>,
    lost: Res<LostEnergy>,
    cleared_bosses: Res<crate::boss::ClearedBosses>,
    cleared_arenas: Res<crate::boss::ClearedArenas>,
    mut boss_fight: ResMut<crate::boss::BossFight>,
    existing: Query<Entity, With<MapEntity>>,
    mut player: Query<(&mut Transform, &mut Velocity), With<Player>>,
) {
    let Some(load) = events.read().last().cloned() else {
        return;
    };

    // Clear the old room.
    for entity in &existing {
        commands.entity(entity).despawn();
    }
    solids.0.clear();

    let Some(handle) = assets.maps.get(&load.map) else {
        warn!("unknown map '{}'", load.map);
        return;
    };
    let Some(map) = map_assets.get(handle) else {
        warn!("map '{}' not loaded yet", load.map);
        return;
    };

    let height = map.tiles.len() as i32;
    let width = map
        .tiles
        .iter()
        .map(|r| r.chars().count())
        .max()
        .unwrap_or(0) as i32;
    let mut start_pos = Vec2::new(2.0 * TILE, 2.0 * TILE);
    // An arena arms on entry unless it's already cleared — permanently (a beaten boss)
    // or just for this checkpoint (any arena, until the next bench rest).
    let is_cleared = cleared_bosses.0.contains(&load.map) || cleared_arenas.0.contains(&load.map);
    let arena_armed = !map.fog_wall.is_empty() && !is_cleared;

    // Movers pick up whatever entity is authored at their cells (a solid, spike, bench,
    // …): map each cell to its mover, with a slot to collect the spawned parts.
    let to_world = |col: i32, row: i32| {
        Vec2::new(
            col as f32 * TILE + TILE / 2.0,
            (height - 1 - row) as f32 * TILE + TILE / 2.0,
        )
    };
    let mover_homes: Vec<Vec2> = map
        .movers
        .iter()
        .map(|m| to_world(m.tiles[0].0, m.tiles[0].1))
        .collect();
    let mut mover_at: HashMap<(i32, i32), usize> = HashMap::new();
    for (mi, m) in map.movers.iter().enumerate() {
        for &cell in &m.tiles {
            mover_at.insert(cell, mi);
        }
    }
    let mut mover_parts: Vec<Vec<(Entity, Vec2, bool)>> = vec![Vec::new(); map.movers.len()];

    for (r, line) in map.tiles.iter().enumerate() {
        let row = height - 1 - r as i32; // flip so row 0 is the top, y points up
        for (c, ch) in line.chars().enumerate() {
            let col = c as i32;
            let center = Vec2::new(
                col as f32 * TILE + TILE / 2.0,
                row as f32 * TILE + TILE / 2.0,
            );
            let Some((entity, solid)) = spawn_cell(
                &mut commands,
                &assets,
                map,
                ch,
                col,
                r as i32,
                center,
                arena_armed,
                &mut start_pos,
            ) else {
                continue;
            };
            if let Some(&mi) = mover_at.get(&(col, r as i32)) {
                // A mover cell: hand the entity to its platform, off the static grid.
                mover_parts[mi].push((entity, center - mover_homes[mi], solid));
            } else if solid {
                solids.0.insert((col, row));
            }
        }
    }

    // Hand each mover the parts it picked up.
    for (mi, m) in map.movers.iter().enumerate() {
        crate::movers::spawn_mover(
            &mut commands,
            m,
            height,
            mover_homes[mi],
            std::mem::take(&mut mover_parts[mi]),
        );
    }

    // Parallax scenery layers for this room (despawned with the room as MapEntity).
    crate::scenery::spawn_scenery(&mut commands, &assets, &map.scenery);

    // Teleporter pads are pure data (no grid glyph) — spawn one per portal at its
    // origin cell, flipping the row so y points up.
    for tp in &map.teleports {
        if (0..width).contains(&tp.origin_col) && (0..height).contains(&tp.origin_row) {
            let world_row = height - 1 - tp.origin_row;
            commands.spawn((
                MapEntity,
                Teleporter {
                    to: tp.to.clone(),
                    dest: (tp.dest_col, tp.dest_row),
                },
                Sprite {
                    image: assets.portal.clone(),
                    custom_size: Some(Vec2::splat(TILE)),
                    ..default()
                },
                Transform::from_xyz(
                    tp.origin_col as f32 * TILE + TILE / 2.0,
                    world_row as f32 * TILE + TILE / 2.0,
                    1.0,
                ),
            ));
        }
    }

    // If the player dropped a bloodstain in this room, place its marker so they can
    // walk back and reclaim the energy (see `crate::stats`).
    if lost.amount > 0 && lost.room == load.map {
        commands.spawn((
            MapEntity,
            Bloodstain,
            Sprite {
                image: assets.orb.clone(),
                custom_size: Some(Vec2::splat(20.0)),
                color: Color::srgb(0.7, 0.85, 1.0),
                ..default()
            },
            Transform::from_xyz(lost.pos.x, lost.pos.y, 3.0),
        ));
    }

    // Arm the arena: spawn its combatants (hidden until you got here) and seal the
    // exits. They were cleared above with the room, so a death/leave resets the fight.
    boss_fight.locked = arena_armed;
    boss_fight.respawn = map.fog_respawn;
    if arena_armed {
        for spawn in &map.fog_wall {
            let world_row = height - 1 - spawn.row;
            let pos = Vec2::new(
                spawn.col as f32 * TILE + TILE / 2.0,
                world_row as f32 * TILE + TILE / 2.0,
            );
            if spawn.boss {
                crate::boss::spawn_boss_at(&mut commands, &assets, spawn.kind, pos);
            } else {
                spawn_enemy(&mut commands, &assets, spawn.kind, pos);
            }
        }
    }

    // Resolve a destination cell (a door's `dest`, a teleporter pad, or a bench; grid
    // coords, row 0 = top) to a world centre, flipping the row so y points up.
    // Out-of-range falls back to `start`.
    let cell_pos = match load.entry {
        Entry::Edge(col, row) | Entry::Teleport(col, row) | Entry::Bench(col, row)
            if (0..width).contains(&col) && (0..height).contains(&row) =>
        {
            let world_row = height - 1 - row;
            Vec2::new(
                col as f32 * TILE + TILE / 2.0,
                world_row as f32 * TILE + TILE / 2.0,
            )
        }
        _ => start_pos,
    };

    let room = Vec2::new(width as f32 * TILE, height as f32 * TILE);
    let pos = entry_position(&load.entry, start_pos, cell_pos);

    // Record the room's name, doors + size for edge detection and the camera.
    *current = CurrentRoom {
        name: load.map.clone(),
        north: map.north.clone(),
        south: map.south.clone(),
        east: map.east.clone(),
        west: map.west.clone(),
        size: room,
    };
    room_view.size = room;
    room_view.snap = true;
    respawn.0 = pos; // dying returns the player to where they entered
    commands.insert_resource(ClearColor(map.bg_color()));

    if let Ok((mut transform, mut velocity)) = player.single_mut() {
        transform.translation.x = pos.x;
        transform.translation.y = pos.y;
        velocity.0 = Vec2::ZERO;
    }
    cooldown.0 = 0.4;
    // Disarm teleporters until the player steps clear, so they don't immediately
    // re-fire on the pad they just landed on (or one under the entry point).
    armed.0 = false;
}

fn tick_cooldown(time: Res<Time>, mut cooldown: ResMut<TransitionCooldown>) {
    cooldown.0 = (cooldown.0 - time.delta_secs()).max(0.0);
}

/// Swap rooms when the player walks off an edge that has a neighbour; if they fall
/// off a bottomless edge (no south neighbour), respawn them where they came in.
fn detect_transitions(
    cooldown: Res<TransitionCooldown>,
    current: Res<CurrentRoom>,
    boss_fight: Res<crate::boss::BossFight>,
    player: Query<&Transform, With<Player>>,
    mut load: MessageWriter<LoadMap>,
    mut hurt: MessageWriter<Hurt>,
) {
    // The fog gate seals the arena: no leaving (or falling out) mid-fight.
    if boss_fight.locked {
        return;
    }
    let Ok(transform) = player.single() else {
        return;
    };
    let pos = transform.translation.truncate();
    let room = current.size;

    if cooldown.0 <= 0.0 {
        // Pick which edge was crossed, then the door on it nearest the crossing point
        // (vertical edges sort by the player's `y`, horizontal edges by `x`).
        let door = if pos.x < 0.0 {
            nearest_door(&current.west, pos.y, room, true)
        } else if pos.x > room.x {
            nearest_door(&current.east, pos.y, room, true)
        } else if pos.y > room.y {
            nearest_door(&current.north, pos.x, room, false)
        } else if pos.y < 0.0 {
            nearest_door(&current.south, pos.x, room, false)
        } else {
            None
        };

        if let Some(door) = door {
            load.write(LoadMap {
                map: door.to.clone(),
                entry: Entry::Edge(door.dest.0, door.dest.1),
            });
            return;
        }
    }

    // Fell into a bottomless pit (no door below): take a hit. The damage system
    // respawns at the room entrance (no ground to knock back to), or the last bench
    // if it was the final heart.
    if pos.y < -TILE && current.south.is_empty() {
        hurt.write(Hurt::Pit);
    }
}

/// The door on an edge nearest the crossing point. `crossing` is the player's position
/// along the edge (world units): `y` on a `vertical` (east/west) edge, otherwise `x`.
fn nearest_door(doors: &[Door], crossing: f32, room: Vec2, vertical: bool) -> Option<&Door> {
    doors.iter().min_by(|a, b| {
        let axis = |d: &Door| {
            if vertical {
                // Grid row 0 is the top, so flip to a world `y`.
                room.y - (d.origin.1 as f32 + 0.5) * TILE
            } else {
                (d.origin.0 as f32 + 0.5) * TILE
            }
        };
        (axis(a) - crossing)
            .abs()
            .total_cmp(&(axis(b) - crossing).abs())
    })
}

/// While the boss arena is sealed, keep the player inside the room: the locked exits
/// leave door openings they could otherwise walk or fall out through.
fn confine_to_arena(
    boss_fight: Res<crate::boss::BossFight>,
    current: Res<CurrentRoom>,
    mut player: Query<&mut Transform, With<Player>>,
) {
    if !boss_fight.locked {
        return;
    }
    let Ok(mut transform) = player.single_mut() else {
        return;
    };
    let room = current.size;
    transform.translation.x = transform
        .translation
        .x
        .clamp(PLAYER_HALF.x, (room.x - PLAYER_HALF.x).max(PLAYER_HALF.x));
    // Floor level (one tile of border + the player's half height): catches a fall
    // through the arena's door gap and sets them back on the floor.
    transform.translation.y = transform.translation.y.max(TILE + PLAYER_HALF.y);
}

/// Send the player to a linked room when they step onto a teleporter pad. A pad
/// fires only when [`TeleportArmed`], which re-arms only once the player is
/// [`TELEPORT_REARM`] clear of every pad — the dead zone between that and the
/// (smaller) trigger stops a single pad chaining teleports or firing on arrival.
fn detect_teleport(
    mut armed: ResMut<TeleportArmed>,
    teleporters: Query<(&Transform, &Teleporter)>,
    player: Query<&Transform, With<Player>>,
    mut load: MessageWriter<LoadMap>,
) {
    let Ok(player_tf) = player.single() else {
        return;
    };
    let player_pos = player_tf.translation.truncate();

    // Re-arm only when well clear of every pad (not merely off the trigger box).
    let clear = teleporters
        .iter()
        .all(|(tf, _)| player_pos.distance(tf.translation.truncate()) > TELEPORT_REARM);
    if clear {
        armed.0 = true;
    }
    if !armed.0 {
        return;
    }

    // Armed and overlapping a pad → teleport, then disarm until clear again.
    if let Some((_, tp)) = teleporters.iter().find(|(tf, _)| {
        let delta = (tf.translation.truncate() - player_pos).abs();
        delta.x < TELEPORT_HALF.x + PLAYER_HALF.x && delta.y < TELEPORT_HALF.y + PLAYER_HALF.y
    }) {
        armed.0 = false;
        load.write(LoadMap {
            map: tp.to.clone(),
            entry: Entry::Teleport(tp.dest.0, tp.dest.1),
        });
    }
}

/// Show a prompt above a bench the player is standing on, and — when they press
/// **interact** there — open the **bench shop** (Rest / upgrade / Leave). The shop
/// itself (resting, buying) lives in [`crate::stats`]; here we just detect the bench
/// and hand it the cell to rest at.
fn bench_interact(
    intent: Res<PlayerIntent>,
    benches: Query<(&Transform, &Bench), Without<BenchPrompt>>,
    player: Query<&Transform, (With<Player>, Without<BenchPrompt>)>,
    mut prompt: Query<(&mut Transform, &mut Visibility), With<BenchPrompt>>,
    mut bench_at: ResMut<BenchAt>,
    mut mode: ResMut<OverlayMode>,
    mut menu: ResMut<NextState<CharMenu>>,
) {
    let Ok(player_tf) = player.single() else {
        return;
    };
    let player_pos = player_tf.translation.truncate();

    // The bench the player is standing on, if any.
    let on_bench = benches.iter().find(|(tf, _)| {
        let delta = (tf.translation.truncate() - player_pos).abs();
        delta.x < BENCH_HALF.x + PLAYER_HALF.x && delta.y < BENCH_HALF.y + PLAYER_HALF.y
    });

    // Show the prompt above that bench, or hide it.
    if let Ok((mut prompt_tf, mut visibility)) = prompt.single_mut() {
        match on_bench {
            Some((tf, _)) => {
                prompt_tf.translation.x = tf.translation.x;
                prompt_tf.translation.y = tf.translation.y + TILE;
                *visibility = Visibility::Visible;
            }
            None => *visibility = Visibility::Hidden,
        }
    }

    // On the interact press, open the bench shop for this bench.
    if intent.interact
        && let Some((_, bench)) = on_bench
    {
        bench_at.0 = Some((bench.col, bench.row));
        *mode = OverlayMode::Bench;
        menu.set(CharMenu::Open);
    }
}

/// Spawn the (initially hidden) bench prompt; [`bench_interact`] positions it.
fn spawn_bench_prompt(mut commands: Commands, existing: Query<(), With<BenchPrompt>>) {
    if !existing.is_empty() {
        return;
    }
    commands.spawn((
        BenchPrompt,
        Text2d::new("[E] bench"),
        TextFont {
            font_size: FontSize::Px(16.0),
            ..default()
        },
        TextColor(Color::srgb(0.96, 0.9, 0.6)),
        Transform::from_xyz(0.0, 0.0, 20.0),
        Visibility::Hidden,
    ));
}

fn despawn_bench_prompt(mut commands: Commands, prompts: Query<Entity, With<BenchPrompt>>) {
    for entity in &prompts {
        commands.entity(entity).despawn();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The binary must carry a complete, valid Story campaign **and** every sprite the
    /// game asks for — so a release exe runs with no `assets/` folder. (No disk or GPU:
    /// `from_buffer` decodes on the CPU.)
    #[test]
    fn embedded_assets_are_self_contained() {
        assert!(!EMBEDDED_STORY_MAPS.is_empty(), "no embedded rooms");
        assert!(
            EMBEDDED_STORY_MAPS.iter().any(|(n, _)| *n == START_MAP),
            "embedded campaign is missing the start room"
        );
        for (name, ron) in EMBEDDED_STORY_MAPS {
            MapData::from_ron(ron).unwrap_or_else(|e| panic!("embedded room '{name}': {e}"));
        }

        let mut wanted = vec![
            "tile.png",
            "player.png",
            "spikes.png",
            "portal.png",
            "bench.png",
            "orb.png",
            "slash.png",
            "rock.png",
            "boss.png",
        ];
        wanted.extend(ENEMY_KINDS.iter().map(|k| k.sheet));
        let mut images = Assets::<Image>::default();
        for name in wanted {
            // Panics with a clear message if a sprite is missing or won't decode.
            embedded_sprite(&mut images, name);
        }
    }

    /// Every room on disk must parse with our RON reader, have content, and only
    /// name neighbours that actually exist.
    #[test]
    fn demo_maps_parse_and_interconnect() {
        let names = discover_rooms(SHIPPED_MAPS_DIR);
        assert!(
            names.len() >= 12,
            "expected at least the 12 demo rooms, found {}",
            names.len()
        );

        let mut maps = HashMap::new();
        for name in &names {
            let path = map_fs_path(SHIPPED_MAPS_DIR, name);
            let text =
                std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));
            let map = MapData::from_ron(&text).unwrap_or_else(|e| panic!("parsing {path}: {e}"));

            assert!(!map.solid.is_empty(), "{name}: empty solid legend");
            assert!(!map.tiles.is_empty(), "{name}: no rows");
            maps.insert(name.clone(), map);
        }

        // Every declared neighbour must reference a real room. (Links need not be
        // symmetric — one-way passages are allowed, and the builder can author
        // rooms — but a dangling link is a bug.)
        for (name, map) in &maps {
            for target in map.linked_rooms() {
                assert!(
                    maps.contains_key(target),
                    "{name}: links to unknown room '{target}'"
                );
            }
            // Teleporters: origin must be in this room and dest in a real room.
            let dims = |m: &MapData| {
                (
                    m.tiles.iter().map(|r| r.chars().count()).max().unwrap_or(0) as i32,
                    m.tiles.len() as i32,
                )
            };
            let (ow, oh) = dims(map);
            for tp in &map.teleports {
                assert!(
                    (0..ow).contains(&tp.origin_col) && (0..oh).contains(&tp.origin_row),
                    "{name}: teleporter origin ({}, {}) out of bounds",
                    tp.origin_col,
                    tp.origin_row
                );
                let dest = maps
                    .get(&tp.to)
                    .unwrap_or_else(|| panic!("{name}: teleporter to unknown room '{}'", tp.to));
                let (dw, dh) = dims(dest);
                assert!(
                    (0..dw).contains(&tp.dest_col) && (0..dh).contains(&tp.dest_row),
                    "{name}: teleporter dest ({}, {}) out of bounds in '{}'",
                    tp.dest_col,
                    tp.dest_row,
                    tp.to
                );
            }
            // Enemy entries must use a real kind and sit on an `E` cell.
            for e in &map.enemies {
                assert!(
                    e.kind < ENEMY_KINDS.len(),
                    "{name}: enemy kind {} out of range",
                    e.kind
                );
                let on_enemy = map
                    .tiles
                    .get(e.row as usize)
                    .and_then(|line| line.chars().nth(e.col as usize))
                    == Some(ENEMY_GLYPH);
                assert!(
                    on_enemy,
                    "{name}: enemy entry ({}, {}) not on an 'E'",
                    e.col, e.row
                );
            }
        }

        // The starting room must contain the start marker.
        let start = &maps[START_MAP];
        assert!(
            start.tiles.iter().any(|r| r.contains(START_MARKER)),
            "{START_MAP}: missing start marker '{START_MARKER}'"
        );
    }

    /// What the level builder writes must round-trip back through our reader.
    #[test]
    fn to_ron_round_trips() {
        let original = MapData {
            name: "Forest Glade".to_string(),
            solid: "#".to_string(),
            spikes: "^".to_string(),
            rocks: "R".to_string(),
            north: vec![Door {
                origin: (1, 0),
                to: "r0_1".to_string(),
                dest: (1, 2),
            }],
            south: Vec::new(),
            east: vec![
                Door {
                    origin: (3, 1),
                    to: "r1_0".to_string(),
                    dest: (0, 1),
                },
                Door {
                    origin: (3, 2),
                    to: "r1_0".to_string(),
                    dest: (0, 2),
                },
            ],
            west: Vec::new(),
            teleports: vec![Teleport {
                origin_col: 1,
                origin_row: 1,
                to: "r1_1".to_string(),
                dest_col: 7,
                dest_row: 2,
            }],
            enemies: vec![EnemySpawn {
                kind: 1,
                col: 2,
                row: 2,
            }],
            fog_wall: vec![ArenaSpawn {
                boss: true,
                kind: 0,
                col: 5,
                row: 6,
            }],
            fog_respawn: true,
            movers: vec![Mover {
                tiles: vec![(5, 5), (6, 5)],
                path: vec![(10, 5), (10, 8)],
                mode: MoveMode::PingPong,
                speed: 60.0,
                rest: 1000.0,
            }],
            scenery: Scenery {
                far: "snowy_mountains".to_string(),
                mid: "forest_meadow".to_string(),
                near: "forest_meadow".to_string(),
                fg: "misty_swamp".to_string(),
            },
            bg: [0.25, 0.5, 0.75],
            tiles: vec![
                "####".to_string(),
                "#T@#".to_string(),
                "#^E#".to_string(),
                "####".to_string(),
            ],
        };

        let parsed = MapData::from_ron(&original.to_ron()).expect("round-trip parse");
        assert_eq!(parsed.name, original.name);
        assert_eq!(parsed.solid, original.solid);
        assert_eq!(parsed.bg, original.bg);
        assert_eq!(parsed.tiles, original.tiles);
        // Doors round-trip: a single north door and two east doors to the same room.
        assert_eq!(parsed.north.len(), 1);
        assert_eq!(parsed.north[0].origin, (1, 0));
        assert_eq!(parsed.north[0].to, "r0_1");
        assert_eq!(parsed.north[0].dest, (1, 2));
        assert!(parsed.south.is_empty());
        assert_eq!(parsed.east.len(), 2);
        assert_eq!(parsed.east[0].origin, (3, 1));
        assert_eq!(parsed.east[1].dest, (0, 2));
        assert!(parsed.west.is_empty());
        assert_eq!(parsed.teleports.len(), 1);
        assert_eq!(parsed.teleports[0].origin_col, 1);
        assert_eq!(parsed.teleports[0].origin_row, 1);
        assert_eq!(parsed.teleports[0].to, "r1_1");
        assert_eq!(parsed.teleports[0].dest_col, 7);
        assert_eq!(parsed.teleports[0].dest_row, 2);
        assert_eq!(parsed.enemies.len(), 1);
        assert_eq!(parsed.enemies[0].kind, 1);
        assert_eq!(parsed.enemies[0].col, 2);
        assert_eq!(parsed.enemies[0].row, 2);
        assert_eq!(parsed.fog_wall.len(), 1);
        assert!(parsed.fog_wall[0].boss);
        assert_eq!(parsed.fog_wall[0].col, 5);
        assert_eq!(parsed.fog_wall[0].row, 6);
        // Movers round-trip: tiles, path, mode, speed, rest.
        assert_eq!(parsed.movers.len(), 1);
        assert_eq!(parsed.movers[0].tiles, vec![(5, 5), (6, 5)]);
        assert_eq!(parsed.movers[0].path, vec![(10, 5), (10, 8)]);
        assert!(parsed.movers[0].mode == MoveMode::PingPong);
        assert_eq!(parsed.movers[0].speed, 60.0);
        assert_eq!(parsed.movers[0].rest, 1000.0);
        // Scenery round-trips per layer (mix-and-match).
        assert_eq!(parsed.scenery.far, "snowy_mountains");
        assert_eq!(parsed.scenery.mid, "forest_meadow");
        assert_eq!(parsed.scenery.near, "forest_meadow");
        assert_eq!(parsed.scenery.fg, "misty_swamp");
    }
}
